export type PortfolioCategory = "packaging" | "brand-literature" | "logos";

export type PortfolioItem = {
  slug: string;
  title: string;
  client: string;
  category: PortfolioCategory;
  tags: string[];
  src: string;
  width: number;
  height: number;
  /** Optional 2-3 sentence "what it needed → what was designed" narrative — sourced from docs/client-requirements.md, no invented outcomes/stats */
  description?: string;
  /** Real production dieline extracted directly from the client's own CorelDRAW (.cdr) source file — only set for slugs independently opened and verified, never generated/guessed. Absent = ProjectModal falls back to the generic illustrative diagram. */
  dielineSrc?: string;
  /** Curated for the flagship / featured showcase */
  isFlagship?: boolean;
  /** Portrait (default) vs wide — set "wide" for landscape source photos */
  cardAspect?: "portrait" | "wide";
  /** Self-directed concept piece — no live client brief. Surfaced as a "Concept Project" badge so it's never mistaken for paid client work. */
  isConcept?: boolean;
};

export const portfolioItems: PortfolioItem[] = [
  {
    slug: "paracetamol-syrup-pediatric",
    title: "Paracetamol Syrup — Pediatric Formula",
    client: "Pharmaceutical Range",
    category: "packaging",
    tags: ["Pharmaceutical", "Syrup Box", "Pediatric Care"],
    src: "/portfolio/packaging/paracetamol-syrup-pediatric-box.webp",
    width: 1122,
    height: 1402,
    isFlagship: true,
    description:
      "A clear, friendly carton for a children's paracetamol syrup — dosage and usage read at a glance. Built to exact dieline and print-ready specs.",
  },
  {
    slug: "paracetamol-tablets-blue",
    title: "Paracetamol Tablets IP 500 mg — Blue Wave Box",
    client: "Pharmaceutical Range",
    category: "packaging",
    tags: ["Pharmaceutical", "Box Design", "10x10 Tablets"],
    src: "/portfolio/packaging/paracetamol-tablets-blue-box.webp",
    width: 1402,
    height: 1122,
    cardAspect: "wide",
    description:
      "A 10x10 tablet carton with clear strength and count labeling, built to the exact printer dieline. The blue wave graphic sets it apart from typical text-heavy medicine boxes.",
  },
  {
    slug: "shri-hanuman-realty-dholera",
    title: "Shri Hanuman Realty — Dholera Smart City Brochure",
    client: "Shri Hanuman Realty",
    category: "brand-literature",
    tags: ["Real Estate", "Trifold Brochure", "Print Literature"],
    src: "/portfolio/brochures-catalogs/shri-hanuman-realty-dholera-brochure.webp",
    width: 1536,
    height: 1024,
    isFlagship: true,
    cardAspect: "wide",
  },
  {
    slug: "kenheal-healthcare-wellness",
    title: "Kenheal Healthcare — Clinical Nutrition & Wellness Portfolio",
    client: "Kenheal Healthcare",
    category: "brand-literature",
    tags: ["Pharmaceutical", "Visual Book", "Brand Literature"],
    src: "/portfolio/brochures-catalogs/kenheal-healthcare-wellness-portfolio.webp",
    width: 1536,
    height: 1024,
    isFlagship: true,
    cardAspect: "wide",
    description:
      "A full visual book for Kenheal Healthcare — cover through inner pages — presenting its clinical nutrition and wellness brand with a clean, consistent layout.",
  },
  {
    slug: "npmakeover-bridal-catalog",
    title: "NP's Makeover — Bridal Package Catalog",
    client: "NP's Makeover",
    category: "brand-literature",
    tags: ["Beauty & Salon", "Catalog Design", "Brand Literature"],
    src: "/portfolio/brochures-catalogs/npmakeover-bridal-catalog.webp",
    width: 1402,
    height: 1122,
    isFlagship: true,
    cardAspect: "wide",
  },
  {
    slug: "medween-pharma-box",
    title: "Medween — Pharma Bottle Box",
    client: "Medween",
    category: "packaging",
    tags: ["Pharmaceutical", "Box Design"],
    src: "/portfolio/packaging/medween-pharma-box.webp",
    width: 1024,
    height: 1024,
    isFlagship: true,
    dielineSrc: "/portfolio/dielines/medween-pharma-box.png",
    description:
      "A compact bottle-box carton for Medween with accurate, compliant product labeling. Finished print-ready with exact bleed and color profiles.",
  },
  {
    slug: "lilaura-lavender",
    title: "Lil'Aura — Lavender Car Freshener",
    client: "Lil'Aura",
    category: "packaging",
    tags: ["Car Freshener", "Box Design"],
    src: "/portfolio/packaging/lilaura-car-freshener-lavender.webp",
    width: 1122,
    height: 1402,
    isFlagship: true,
  },
  {
    slug: "lilaura-oudh",
    title: "Lil'Aura — Oudh Wood Car Freshener",
    client: "Lil'Aura",
    category: "packaging",
    tags: ["Car Freshener", "Box Design"],
    src: "/portfolio/packaging/lilaura-car-freshener-oudh-wood.webp",
    width: 1122,
    height: 1402,
  },
  {
    slug: "madburgs-burger-box",
    title: "Madburgs — Burger Box",
    client: "Madburgs",
    category: "packaging",
    tags: ["Food & Snack", "Box Design"],
    src: "/portfolio/packaging/madburgs-burger-box.webp",
    width: 1402,
    height: 1122,
    isFlagship: true,
    dielineSrc: "/portfolio/dielines/madburgs-burger-box.png",
  },
  {
    slug: "aqua-water-filter",
    title: "Aqua — Water Filter Packaging Set",
    client: "Aqua",
    category: "packaging",
    tags: ["Health", "Box Design", "Product Range"],
    src: "/portfolio/packaging/aqua-water-filter-packaging-set.webp",
    width: 1536,
    height: 1024,
    cardAspect: "wide",
  },
  {
    slug: "siriza-herbal-soap",
    title: "Siriza — Premium Herbal Soap Box",
    client: "Siriza",
    category: "packaging",
    tags: ["Personal Care", "Box Design"],
    src: "/portfolio/packaging/siriza-herbal-soap-box.webp",
    width: 1264,
    height: 842,
    dielineSrc: "/portfolio/dielines/siriza-herbal-soap.png",
  },
  {
    slug: "jalaram-gota",
    title: "Jalaram — Gota Instant Mix",
    client: "Jalaram",
    category: "packaging",
    tags: ["Food & Snack", "Box Design"],
    src: "/portfolio/packaging/jalaram-gota-food-box.png",
    width: 1470,
    height: 1070,
    dielineSrc: "/portfolio/dielines/jalaram-gota.png",
  },
  {
    slug: "pris-kitchen-simple-khakhra",
    title: "Pri's Kitchen — Simple Khakhra Box",
    client: "Pri's Kitchen",
    category: "packaging",
    tags: ["Food & Snack", "Box Design"],
    src: "/portfolio/packaging/pris-kitchen-simple-khakhra-box.webp",
    width: 1254,
    height: 1254,
  },
  {
    slug: "pris-kitchen-cheese-khakhra",
    title: "Pri's Kitchen — Cheese Khakhra Box",
    client: "Pri's Kitchen",
    category: "packaging",
    tags: ["Food & Snack", "Box Design"],
    src: "/portfolio/packaging/pris-kitchen-cheese-khakhra-box.webp",
    width: 1374,
    height: 1145,
  },
  {
    slug: "pris-kitchen-jeera-khakhra",
    title: "Pri's Kitchen — Jeera Khakhra Box",
    client: "Pri's Kitchen",
    category: "packaging",
    tags: ["Food & Snack", "Box Design"],
    src: "/portfolio/packaging/pris-kitchen-jeera-khakhra-box.webp",
    width: 1254,
    height: 1254,
  },
  {
    slug: "pris-kitchen-methi-khakhra",
    title: "Pri's Kitchen — Methi Khakhra Box",
    client: "Pri's Kitchen",
    category: "packaging",
    tags: ["Food & Snack", "Box Design"],
    src: "/portfolio/packaging/pris-kitchen-methi-khakhra-box.webp",
    width: 1246,
    height: 1262,
  },
  {
    slug: "pris-kitchen-peri-peri-khakhra",
    title: "Pri's Kitchen — Peri Peri Khakhra Box",
    client: "Pri's Kitchen",
    category: "packaging",
    tags: ["Food & Snack", "Box Design"],
    src: "/portfolio/packaging/pris-kitchen-peri-peri-khakhra-box.webp",
    width: 1254,
    height: 1254,
  },
  {
    slug: "maru-botanics-ubtan-powder",
    title: "Maru Botanics — Ubtan Powder Box",
    client: "Maru Botanics",
    category: "packaging",
    tags: ["Ayurvedic & Herbal", "Box Design"],
    src: "/portfolio/packaging/maru-botanics-ubtan-powder-box.webp",
    width: 1147,
    height: 1371,
  },
  {
    slug: "tsd-world-cable",
    title: "TSD World — Type-C Braided Cable",
    client: "TSD World",
    category: "packaging",
    tags: ["Electronics", "Box Design"],
    src: "/portfolio/packaging/tsd-world-cable-box.webp",
    width: 1536,
    height: 1024,
    cardAspect: "wide",
    dielineSrc: "/portfolio/dielines/tsd-world-cable.png",
  },
  {
    slug: "plugd-usb-c-cable",
    title: "Unplugd — USB-C Silicone Braided Cable Box",
    client: "Unplugd",
    category: "packaging",
    tags: ["Electronics", "Box Design"],
    src: "/portfolio/packaging/plugd-usb-c-cable-box.webp",
    width: 1374,
    height: 1145,
  },
  {
    slug: "plugd-usb-c-cable-nylon",
    title: "Unplugd — USB-C Nylon Braided Cable Box",
    client: "Unplugd",
    category: "packaging",
    tags: ["Electronics", "Box Design"],
    src: "/portfolio/packaging/plugd-usb-c-cable-nylon-box.webp",
    width: 1230,
    height: 1278,
  },
  {
    slug: "peptidesdepot-research-powder",
    title: "PeptidesDepot — Research Powder Box",
    client: "PeptidesDepot",
    category: "packaging",
    tags: ["Pharmaceutical", "Box Design"],
    src: "/portfolio/packaging/peptidesdepot-research-powder-box.webp",
    width: 1536,
    height: 1024,
    cardAspect: "wide",
    description:
      "A research powder carton for PeptidesDepot with clear, lab-appropriate product identification — distinct in tone from a retail medicine box. Built to precise dieline and print-ready standards.",
  },
  {
    slug: "taj-wood-paint-tin",
    title: "Taj Wood Paints — Wood Finish Tin Label",
    client: "Taj Wood Paints",
    category: "packaging",
    tags: ["Home Improvement", "Label Design"],
    src: "/portfolio/packaging/taj-wood-paint-tin.webp",
    width: 1541,
    height: 1021,
    cardAspect: "wide",
    dielineSrc: "/portfolio/dielines/taj-wood-paint-tin.png",
  },
  {
    slug: "kdm-gugal-dhoop-cup",
    title: "KDM Pujan Samagri — Kapoor Gugal Sambrani Dhoop Cup Box",
    client: "KDM Pujan Samagri",
    category: "packaging",
    tags: ["Devotional & Religious", "Box Design"],
    src: "/portfolio/packaging/kdm-gugal-dhoop-cup-box.webp",
    width: 1122,
    height: 1402,
    dielineSrc: "/portfolio/dielines/kdm-gugal-dhoop-cup.png",
  },
  {
    slug: "prince-pipes-puja-kit",
    title: "Prince Pipes — Ganesh Chaturthi Puja Kit",
    client: "Prince Pipes",
    category: "packaging",
    tags: ["Devotional & Religious", "Box Design", "Corporate Gifting"],
    src: "/portfolio/packaging/prince-pipes-puja-kit-box.webp",
    width: 1114,
    height: 1412,
    dielineSrc: "/portfolio/dielines/prince-pipes-puja-kit.png",
  },
  {
    slug: "globiomed-pharma-book",
    title: "Globiomed Life Science — Pharma Visual Book",
    client: "Globiomed",
    category: "brand-literature",
    tags: ["Pharmaceutical", "Visual Book", "Brand Literature"],
    src: "/portfolio/brochures-catalogs/globiomed-pharma-visual-book.webp",
    width: 1536,
    height: 1024,
    cardAspect: "wide",
    description:
      "A full visual book for Globiomed Life Science — cover through inner pages — presenting its pharmaceutical brand with a clean, consistent layout, built to the same print-ready standard as the rest of the literature work.",
  },
  {
    slug: "prio-technology-logo",
    title: "Prio Technology — Brand Identity & Logo Mark",
    client: "Prio Technology",
    category: "logos",
    tags: ["Branding", "Logo Design", "Brand Identity"],
    src: "/portfolio/logos/prio-technology-logo.png",
    width: 1600,
    height: 1128,
    isFlagship: true,
    cardAspect: "wide",
  },
  {
    slug: "pep-love-logo",
    title: "Pep Love — Clothing Brand Logo",
    client: "Pep Love",
    category: "logos",
    tags: ["Branding", "Logo Design", "Apparel"],
    src: "/portfolio/logos/pep-love-logo.webp",
    width: 1161,
    height: 1160,
  },
  {
    slug: "ekam-by-seri-logo",
    title: "Ekam by Seri — Brand Logo",
    client: "Ekam by Seri",
    category: "logos",
    tags: ["Branding", "Logo Design"],
    src: "/portfolio/logos/ekam-by-seri-logo.webp",
    width: 1572,
    height: 1110,
  },
  {
    slug: "maru-botanics-multani-powder",
    title: "Maru Botanics — Multani Powder Box",
    client: "Maru Botanics",
    category: "packaging",
    tags: ["Ayurvedic & Herbal", "Box Design"],
    src: "/portfolio/packaging/maru-botanics-multani-powder-box.webp",
    width: 1148,
    height: 1371,
  },
];

export const portfolioFilters: { label: string; value: "all" | PortfolioCategory | "pharma" }[] = [
  { label: "All Work", value: "all" },
  { label: "Packaging", value: "packaging" },
  { label: "Brand Literature", value: "brand-literature" },
  { label: "Logos & Branding", value: "logos" },
  { label: "Pharma & Healthcare", value: "pharma" },
];
