export type PortfolioCategory = "packaging" | "brand-literature" | "logos";

export type PortfolioItem = {
  slug: string;
  title: string;
  client: string;
  category: PortfolioCategory;
  tags: string[];
  src: string;
  width: number;
  height: number;
  /** Optional 2-3 sentence "what it needed → what was designed" narrative — sourced from docs/client-requirements.md, no invented outcomes/stats */
  description?: string;
  /** Real production dieline extracted directly from the client's own CorelDRAW (.cdr) source file — only set for slugs independently opened and verified, never generated/guessed. Absent = ProjectModal falls back to the generic illustrative diagram. */
  dielineSrc?: string;
  /** Curated for the flagship / featured showcase */
  isFlagship?: boolean;
  /** Portrait (default) vs wide — set "wide" for landscape source photos */
  cardAspect?: "portrait" | "wide";
};

export const portfolioItems: PortfolioItem[] = [
  {
    slug: "organic-amla-powder",
    title: "Organic Amla Powder — Ayurvedic Herbal Box",
    client: "Organic Amla",
    category: "packaging",
    tags: ["Ayurvedic & Herbal", "Box Design", "Retail Packaging"],
    src: "/portfolio/packaging/organic-amla-powder-box.png",
    width: 1024,
    height: 1536,
    isFlagship: true,
  },
  {
    slug: "paracetamol-syrup-pediatric",
    title: "Paracetamol Syrup — Pediatric Formula",
    client: "Pharmaceutical Range",
    category: "packaging",
    tags: ["Pharmaceutical", "Syrup Box", "Pediatric Care"],
    src: "/portfolio/packaging/paracetamol-syrup-pediatric-box.png",
    width: 1122,
    height: 1402,
    isFlagship: true,
    description:
      "A pediatric paracetamol syrup carton needed dosage and usage information to read clearly at a glance, plus a friendlier, more approachable visual tone than a typical adult medicine box. The design keeps that label hierarchy simple and legible while working within the exact dieline and print-ready specs the format requires.",
  },
  {
    slug: "paracetamol-tablets-blue",
    title: "Paracetamol Tablets IP 500 mg — Blue Wave Box",
    client: "Pharmaceutical Range",
    category: "packaging",
    tags: ["Pharmaceutical", "Box Design", "10x10 Tablets"],
    src: "/portfolio/packaging/paracetamol-tablets-blue-box.png",
    width: 1402,
    height: 1122,
    cardAspect: "wide",
    description:
      "A 10x10 tablet strip carton needed to read clearly as a standard pharmaceutical pack — accurate strength and count labeling — built to the exact dieline the printer runs against. The blue wave graphic gives the pack a distinct shelf identity within an otherwise text-heavy, regulated layout.",
  },
  {
    slug: "shri-hanuman-realty-dholera",
    title: "Shri Hanuman Realty — Dholera Smart City Brochure",
    client: "Shri Hanuman Realty",
    category: "brand-literature",
    tags: ["Real Estate", "Trifold Brochure", "Print Literature"],
    src: "/portfolio/brochures-catalogs/shri-hanuman-realty-dholera-brochure.png",
    width: 1536,
    height: 1024,
    isFlagship: true,
    cardAspect: "wide",
  },
  {
    slug: "kenheal-healthcare-wellness",
    title: "Kenheal Healthcare — Clinical Nutrition & Wellness Portfolio",
    client: "Kenheal Healthcare",
    category: "brand-literature",
    tags: ["Pharmaceutical", "Visual Book", "Brand Literature"],
    src: "/portfolio/brochures-catalogs/kenheal-healthcare-wellness-portfolio.png",
    width: 1536,
    height: 1024,
    isFlagship: true,
    cardAspect: "wide",
    description:
      "Kenheal Healthcare needed a full-booklet visual book — cover through inner pages — that presents its clinical nutrition and wellness brand with a consistent, professional layout. It follows the same company-literature format used for other technical/medical literature in this practice.",
  },
  {
    slug: "npmakeover-bridal-catalog",
    title: "NP's Makeover — Bridal Package Catalog",
    client: "NP's Makeover",
    category: "brand-literature",
    tags: ["Beauty & Salon", "Catalog Design", "Brand Literature"],
    src: "/portfolio/brochures-catalogs/npmakeover-bridal-catalog.png",
    width: 1402,
    height: 1122,
    isFlagship: true,
    cardAspect: "wide",
  },
  {
    slug: "medween-pharma-box",
    title: "Medween — Pharma Bottle Box",
    client: "Medween",
    category: "packaging",
    tags: ["Pharmaceutical", "Box Design"],
    src: "/portfolio/packaging/medween-pharma-box.png",
    width: 1024,
    height: 1024,
    isFlagship: true,
    dielineSrc: "/portfolio/dielines/medween-pharma-box.png",
    description:
      "A pharma bottle carton for Medween needed to present accurate, compliant product labeling within a compact bottle-box dieline. It was finished to the same print-ready standard — exact bleeds and color profiles — used across the rest of the packaging practice.",
  },
  {
    slug: "lilaura-lavender",
    title: "Lil'Aura — Lavender Car Freshener",
    client: "Lil'Aura",
    category: "packaging",
    tags: ["Cosmetics", "Box Design"],
    src: "/portfolio/packaging/lilaura-car-freshener-lavender.png",
    width: 1122,
    height: 1402,
    isFlagship: true,
  },
  {
    slug: "lilaura-oudh",
    title: "Lil'Aura — Oudh Wood Car Freshener",
    client: "Lil'Aura",
    category: "packaging",
    tags: ["Cosmetics", "Box Design"],
    src: "/portfolio/packaging/lilaura-car-freshener-oudh-wood.png",
    width: 1122,
    height: 1402,
  },
  {
    slug: "madburgs-burger-box",
    title: "Madburgs — Burger Box",
    client: "Madburgs",
    category: "packaging",
    tags: ["Food & Snack", "Box Design"],
    src: "/portfolio/packaging/madburgs-burger-box.png",
    width: 1402,
    height: 1122,
    isFlagship: true,
    dielineSrc: "/portfolio/dielines/madburgs-burger-box.png",
  },
  {
    slug: "aqua-water-filter",
    title: "Aqua — Water Filter Packaging Set",
    client: "Aqua",
    category: "packaging",
    tags: ["Health", "Box Design", "Product Range"],
    src: "/portfolio/packaging/aqua-water-filter-packaging-set.png",
    width: 1536,
    height: 1024,
    cardAspect: "wide",
  },
  {
    slug: "siriza-herbal-soap",
    title: "Siriza — Premium Herbal Soap Box",
    client: "Siriza",
    category: "packaging",
    tags: ["Cosmetics", "Box Design"],
    src: "/portfolio/packaging/siriza-herbal-soap-box.png",
    width: 1264,
    height: 842,
    dielineSrc: "/portfolio/dielines/siriza-herbal-soap.png",
  },
  {
    slug: "jalaram-gota",
    title: "Jalaram — Gota Instant Mix",
    client: "Jalaram",
    category: "packaging",
    tags: ["Food & Snack", "Box Design"],
    src: "/portfolio/packaging/jalaram-gota-food-box.png",
    width: 1206,
    height: 880,
    dielineSrc: "/portfolio/dielines/jalaram-gota.png",
  },
  {
    slug: "tsd-world-cable",
    title: "TSD World — Type-C Braided Cable",
    client: "TSD World",
    category: "packaging",
    tags: ["Electronics", "Box Design"],
    src: "/portfolio/packaging/tsd-world-cable-box.png",
    width: 1536,
    height: 1024,
    cardAspect: "wide",
    dielineSrc: "/portfolio/dielines/tsd-world-cable.png",
  },
  {
    slug: "peptidesdepot-research-powder",
    title: "PeptidesDepot — Research Powder Box",
    client: "PeptidesDepot",
    category: "packaging",
    tags: ["Pharmaceutical", "Box Design"],
    src: "/portfolio/packaging/peptidesdepot-research-powder-box.png",
    width: 1536,
    height: 1024,
    cardAspect: "wide",
    description:
      "A research powder carton for PeptidesDepot needed clear product identification suited to a laboratory/research-use product, distinct in tone from a retail medicine box. It was built to the same precise dieline and print-ready file standard as the rest of the packaging work.",
  },
  {
    slug: "taj-wood-paint-tin",
    title: "Taj Wood Paints — Wood Finish Tin Label",
    client: "Taj Wood Paints",
    category: "packaging",
    tags: ["Home Improvement", "Label Design"],
    src: "/portfolio/packaging/taj-wood-paint-tin.png",
    width: 1541,
    height: 1021,
    cardAspect: "wide",
    dielineSrc: "/portfolio/dielines/taj-wood-paint-tin.png",
  },
  {
    slug: "kdm-gugal-dhoop-cup",
    title: "KDM Pujan Samagri — Kapoor Gugal Sambrani Dhoop Cup Box",
    client: "KDM Pujan Samagri",
    category: "packaging",
    tags: ["Devotional & Religious", "Box Design"],
    src: "/portfolio/packaging/kdm-gugal-dhoop-cup-box.png",
    width: 1122,
    height: 1402,
    dielineSrc: "/portfolio/dielines/kdm-gugal-dhoop-cup.png",
  },
  {
    slug: "prince-pipes-puja-kit",
    title: "Prince Pipes — Ganesh Chaturthi Puja Kit",
    client: "Prince Pipes",
    category: "packaging",
    tags: ["Devotional & Religious", "Box Design", "Corporate Gifting"],
    src: "/portfolio/packaging/prince-pipes-puja-kit-box.png",
    width: 1114,
    height: 1412,
    dielineSrc: "/portfolio/dielines/prince-pipes-puja-kit.png",
  },
  {
    slug: "littlegrow-baby-cereal",
    title: "LittleGrow — Baby Cereal Box",
    client: "LittleGrow",
    category: "packaging",
    tags: ["Baby Products", "Box Design"],
    src: "/portfolio/baby-products/littlegrow-baby-cereal-box.png",
    width: 718,
    height: 575,
  },
  {
    slug: "globiomed-pharma-book",
    title: "Globiomed Life Science — Pharma Visual Book",
    client: "Globiomed",
    category: "brand-literature",
    tags: ["Pharmaceutical", "Brochure"],
    src: "/portfolio/brochures-catalogs/globiomed-pharma-visual-book.png",
    width: 1536,
    height: 1024,
    cardAspect: "wide",
  },
  {
    slug: "prio-technology-logo",
    title: "Prio Technology — Brand Identity & Logo Mark",
    client: "Prio Technology",
    category: "logos",
    tags: ["Branding", "Logo Design", "Brand Identity"],
    src: "/portfolio/logos/prio-technology-logo.png",
    width: 1600,
    height: 1128,
    isFlagship: true,
    cardAspect: "wide",
  },
  {
    slug: "logo-design-grid",
    title: "Logo Design — Selected Marks",
    client: "Various clients",
    category: "logos",
    tags: ["Branding", "Logo Design"],
    src: "/portfolio/logos/logo-design-grid.png",
    width: 1600,
    height: 1075,
    isFlagship: true,
  },
];

export const portfolioFilters: { label: string; value: "all" | PortfolioCategory | "pharma" }[] = [
  { label: "All Work", value: "all" },
  { label: "Packaging", value: "packaging" },
  { label: "Brand Literature", value: "brand-literature" },
  { label: "Logos & Branding", value: "logos" },
  { label: "Pharma & Healthcare", value: "pharma" },
];
