export type PortfolioCategory = "packaging" | "brand-literature" | "logos";

export type PortfolioItem = {
  slug: string;
  title: string;
  client: string;
  category: PortfolioCategory;
  tags: string[];
  src: string;
  width: number;
  height: number;
  /** Curated for the flagship / featured showcase */
  isFlagship?: boolean;
  /** Portrait (default) vs wide — set "wide" for landscape source photos */
  cardAspect?: "portrait" | "wide";
};

export const portfolioItems: PortfolioItem[] = [
  {
    slug: "organic-amla-powder",
    title: "Organic Amla Powder — Ayurvedic Herbal Box",
    client: "Organic Amla",
    category: "packaging",
    tags: ["Ayurvedic & Herbal", "Box Design", "Retail Packaging"],
    src: "/portfolio/packaging/organic-amla-powder-box.png",
    width: 1024,
    height: 1536,
    isFlagship: true,
  },
  {
    slug: "paracetamol-syrup-pediatric",
    title: "Paracetamol Syrup — Pediatric Formula",
    client: "Pharmaceutical Range",
    category: "packaging",
    tags: ["Pharmaceutical", "Syrup Box", "Pediatric Care"],
    src: "/portfolio/packaging/paracetamol-syrup-pediatric-box.png",
    width: 1122,
    height: 1402,
    isFlagship: true,
  },
  {
    slug: "paracetamol-tablets-blue",
    title: "Paracetamol Tablets IP 500 mg — Blue Wave Box",
    client: "Pharmaceutical Range",
    category: "packaging",
    tags: ["Pharmaceutical", "Box Design", "10x10 Tablets"],
    src: "/portfolio/packaging/paracetamol-tablets-blue-box.png",
    width: 1402,
    height: 1122,
    cardAspect: "wide",
  },
  {
    slug: "shri-hanuman-realty-dholera",
    title: "Shri Hanuman Realty — Dholera Smart City Brochure",
    client: "Shri Hanuman Realty",
    category: "brand-literature",
    tags: ["Real Estate", "Trifold Brochure", "Print Literature"],
    src: "/portfolio/brochures-catalogs/shri-hanuman-realty-dholera-brochure.png",
    width: 1536,
    height: 1024,
    isFlagship: true,
    cardAspect: "wide",
  },
  {
    slug: "kenheal-healthcare-wellness",
    title: "Kenheal Healthcare — Clinical Nutrition & Wellness Portfolio",
    client: "Kenheal Healthcare",
    category: "brand-literature",
    tags: ["Pharmaceutical", "Visual Book", "Brand Literature"],
    src: "/portfolio/brochures-catalogs/kenheal-healthcare-wellness-portfolio.png",
    width: 1536,
    height: 1024,
    isFlagship: true,
    cardAspect: "wide",
  },
  {
    slug: "npmakeover-bridal-catalog",
    title: "NP's Makeover — Bridal Package Catalog",
    client: "NP's Makeover",
    category: "brand-literature",
    tags: ["Beauty & Salon", "Catalog Design", "Brand Literature"],
    src: "/portfolio/brochures-catalogs/npmakeover-bridal-catalog.png",
    width: 1402,
    height: 1122,
    isFlagship: true,
    cardAspect: "wide",
  },
  {
    slug: "medween-pharma-box",
    title: "Medween — Pharma Bottle Box",
    client: "Medween",
    category: "packaging",
    tags: ["Pharmaceutical", "Box Design"],
    src: "/portfolio/packaging/medween-pharma-box.png",
    width: 1024,
    height: 1024,
    isFlagship: true,
  },
  {
    slug: "lilaura-lavender",
    title: "Lil'Aura — Lavender Car Freshener",
    client: "Lil'Aura",
    category: "packaging",
    tags: ["Cosmetics", "Box Design"],
    src: "/portfolio/packaging/lilaura-car-freshener-lavender.png",
    width: 1122,
    height: 1402,
    isFlagship: true,
  },
  {
    slug: "lilaura-oudh",
    title: "Lil'Aura — Oudh Wood Car Freshener",
    client: "Lil'Aura",
    category: "packaging",
    tags: ["Cosmetics", "Box Design"],
    src: "/portfolio/packaging/lilaura-car-freshener-oudh-wood.png",
    width: 1122,
    height: 1402,
  },
  {
    slug: "madburgs-burger-box",
    title: "Madburgs — Burger Box",
    client: "Madburgs",
    category: "packaging",
    tags: ["Food & Snack", "Box Design"],
    src: "/portfolio/packaging/madburgs-burger-box.png",
    width: 1402,
    height: 1122,
    isFlagship: true,
  },
  {
    slug: "aqua-water-filter",
    title: "Aqua — Water Filter Packaging Set",
    client: "Aqua",
    category: "packaging",
    tags: ["Health", "Box Design", "Product Range"],
    src: "/portfolio/packaging/aqua-water-filter-packaging-set.png",
    width: 1536,
    height: 1024,
    cardAspect: "wide",
  },
  {
    slug: "siriza-herbal-soap",
    title: "Siriza — Premium Herbal Soap Box",
    client: "Siriza",
    category: "packaging",
    tags: ["Cosmetics", "Box Design"],
    src: "/portfolio/packaging/siriza-herbal-soap-box.png",
    width: 1264,
    height: 842,
  },
  {
    slug: "jalaram-gota",
    title: "Jalaram — Gota Instant Mix",
    client: "Jalaram",
    category: "packaging",
    tags: ["Food & Snack", "Box Design"],
    src: "/portfolio/packaging/jalaram-gota-food-box.png",
    width: 1206,
    height: 880,
  },
  {
    slug: "tsd-world-cable",
    title: "TSD World — Type-C Braided Cable",
    client: "TSD World",
    category: "packaging",
    tags: ["Electronics", "Box Design"],
    src: "/portfolio/packaging/tsd-world-cable-box.png",
    width: 1536,
    height: 1024,
    cardAspect: "wide",
  },
  {
    slug: "peptidesdepot-research-powder",
    title: "PeptidesDepot — Research Powder Box",
    client: "PeptidesDepot",
    category: "packaging",
    tags: ["Pharmaceutical", "Box Design"],
    src: "/portfolio/packaging/peptidesdepot-research-powder-box.png",
    width: 1536,
    height: 1024,
    cardAspect: "wide",
  },
  {
    slug: "taj-wood-paint-tin",
    title: "Taj Wood Paints — Wood Finish Tin Label",
    client: "Taj Wood Paints",
    category: "packaging",
    tags: ["Home Improvement", "Label Design"],
    src: "/portfolio/packaging/taj-wood-paint-tin.png",
    width: 1541,
    height: 1021,
    cardAspect: "wide",
  },
  {
    slug: "littlegrow-baby-cereal",
    title: "LittleGrow — Baby Cereal Box",
    client: "LittleGrow",
    category: "packaging",
    tags: ["Baby Products", "Box Design"],
    src: "/portfolio/baby-products/littlegrow-baby-cereal-box.png",
    width: 718,
    height: 575,
  },
  {
    slug: "globiomed-pharma-book",
    title: "Globiomed Life Science — Pharma Visual Book",
    client: "Globiomed",
    category: "brand-literature",
    tags: ["Pharmaceutical", "Brochure"],
    src: "/portfolio/brochures-catalogs/globiomed-pharma-visual-book.png",
    width: 1536,
    height: 1024,
    cardAspect: "wide",
  },
  {
    slug: "prio-technology-logo",
    title: "Prio Technology — Brand Identity & Logo Mark",
    client: "Prio Technology",
    category: "logos",
    tags: ["Branding", "Logo Design", "Brand Identity"],
    src: "/portfolio/logos/prio-technology-logo.png",
    width: 1600,
    height: 1128,
    isFlagship: true,
    cardAspect: "wide",
  },
  {
    slug: "logo-design-grid",
    title: "Logo Design — Selected Marks",
    client: "Various clients",
    category: "logos",
    tags: ["Branding", "Logo Design"],
    src: "/portfolio/logos/logo-design-grid.png",
    width: 1600,
    height: 1075,
    isFlagship: true,
  },
];

export const portfolioFilters: { label: string; value: "all" | PortfolioCategory }[] = [
  { label: "All Work", value: "all" },
  { label: "Packaging", value: "packaging" },
  { label: "Brand Literature", value: "brand-literature" },
  { label: "Logos & Branding", value: "logos" },
];
